// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: P4_5inch_Test

#ifndef _P4_5INCH_TEST_UI_H
#define _P4_5INCH_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
void ui_event_ButtonON(lv_event_t * e);
extern lv_obj_t * ui_ButtonON;
extern lv_obj_t * ui_LabelON;
void ui_event_ButtonOFF(lv_event_t * e);
extern lv_obj_t * ui_ButtonOFF;
extern lv_obj_t * ui_LabelOFF;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_table_lamp300_png);    // assets/table_lamp300.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
