// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: P4_5inch_Test

#include "ui.h"
#include "bsp_extra.h"

void LedOn(lv_event_t * e)
{
	// Your code here
	gpio_extra_set_level(true);
}

void LedOff(lv_event_t * e)
{
	// Your code here
	gpio_extra_set_level(false);
}